[package]
name = "monkey-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
itertools = "0.12.1"
lazy_static = "1.4.0"
whoami = "1.4.1"
